---
title: "master"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(dplyr)
library(Hmisc)
```

## GenPop Stress main figures & tables

This is a master script for the main figures and tables in R.

```{r gpstress, include=FALSE}
# load decision-making trial data
load('../../data/gpstress_all_trials.RData')
# load fits and stress data
load('../../data/gpfitsstress.RData')
# load R-squared for individual nc (DS) and dw (DW) fits
load('../../data/ds_r2.RData')
load('../../data/dw_r2.RData')
load('../../data/risk_r2.RData')
# load fitted draws for example subject
load('../../data/ds_subj.RData')
load('../../data/dw_subj.RData')
load('../../data/risk_subj.RData')
# load posteriors
load('../../data/ds_posterior.RData')
load('../../data/dw_posterior.RData')
load('../../data/risk_posterior.RData')
load('../../data/kapparisk_posterior.RData')
```

## Subject's Plots Fig. 2b

```{r fig2abc, echo=FALSE}
source("gp_subjfigsource.R")
ds_trials = genpop_trials %>% filter(sessid_5!=3) %>% droplevels()
dw_trials = genpop_trials %>% filter(sessid_5!=1) %>% filter(sessid_5!=2) %>% droplevels()
subjids <- c(14)
fig2b(ds_trials,ds_fits,ds_r2)
```

## Fig. 3b

```{r fig3b, echo=FALSE}
source("gp_fig3bsource.R")
fig3b(dfjstr)
```

## Stress Behavior Correlation Analysis

```{r corrstressbehavior, echo=FALSE}
source("gp_stressbehavior_cor.R")
# between-subject
corpl_bs(ds_fits, ds12_fits, dw_fits, mf, dfjstr)
# within-subject
corpl_ws(ds_fits, ds12_fits, dw_fits, mf, dfjstr)

# Print significant correlations
bs_sigcor(ds_fits, ds12_fits, dw_fits, mf, dfjstr)
# after Bonferroni (0.05/13)
# K_S.x PC2	0.523458641394442	0.00148882999936909
# PL_S1 PC2	-0.518484035051397	0.00168171266321913
ws_sigcor(ds_fits, ds12_fits, dw_fits, mf, dfjstr)
# after Bonferroni (0.05/6)
# PL_Sd2 ldh3	-0.486201011034419	0.00264282957402134
```

## SI

## Fig. S4a

```{r figS4a, echo=FALSE}
source("gp_figS4absource.R")
figS4a(ds_posterior)
```

## Fig. S4b

```{r figS4b, echo=FALSE}
source("gp_figS4absource.R")
figS4b(dw_posterior)
```


## Fig. S6

```{r figs6, echo=FALSE}
source("gp_figS6source.R")
figs6(dfjstr,4)
```

## Fig. S6 c, table insert based on the figure

```{r figs6i, echo=FALSE}
source("gp_figS6source.R")
# four largest loadings (from bottom to top) per PC
loads = pca_loads(dfjstr,4)
plot_pc4(loads)
```

## Table S4, PCA angles

```{r tables4, echo=FALSE}
source("gp_figS6source.R")
table2(dfjstr,1:2)
table2(dfjstr,2:3)
```

## Table S5, within-subject correlation

```{r tables5, echo=FALSE}
source("gp_tabS56source.R")
delay_fits = left_join(ds_fits,ds12_fits,by = "subjid")
dw_fits$K_D = dw_fits$K_L
dw_fitsX = subset(dw_fits, select = c(K_D, subjid) )
allfits = merge(delay_fits,dw_fitsX, by='subjid')
mbmf = merge(allfits,mf, by='subjid')
mbmfstr = merge(mbmf, dfjstr, by = "subjid")
mbmfstr$K_S21 = mbmfstr$K_S.y-mbmfstr$K_S.x
mbmfstr$PL_S21 = mbmfstr$PL_S2-mbmfstr$PL_S1
mbmfstr$K_L21 = mbmfstr$K_L.y-mbmfstr$K_L.x
mbmfstr$PL_L21 = mbmfstr$PL_L2-mbmfstr$PL_L1
mbmfstr$K_L31 = mbmfstr$K_D-mbmfstr$K_L.x
mbmfstr$PL_L31 = mbmfstr$PL_D-mbmfstr$PL_L1
mbmfstr$K_L32 = mbmfstr$K_D-mbmfstr$K_L.y
mbmfstr$PL_L32 = mbmfstr$PL_D-mbmfstr$PL_L2
mbmft = dplyr::select(mbmfstr,c(K_S21, PL_S21, K_L21, PL_L21, K_L31, PL_L31, K_L32, PL_L32, lds2,lds3,lds32,ldh2,ldh3,ldh32))
# with outlier
resmbmft = table4(mbmft)
resmbmft
#resmbmft$P<0.05
```

## Table S6, between-subject correlation

```{r tables6, echo=FALSE}
source("gp_tabS56source.R")
delay_fits = left_join(ds_fits,ds12_fits,by = "subjid")
dw_fits$K_D = dw_fits$K_L
dw_fitsX = subset(dw_fits, select = c(K_D, subjid) )
allfits = merge(delay_fits,dw_fitsX, by='subjid')
mbmf = merge(allfits,mf, by='subjid')
mbmfstr = merge(mbmf, dfjstr, by = "subjid")
mbmftb = dplyr::select(mbmfstr,c(K_S.x, PL_S1, K_S.y, PL_S2, K_L.x, K_L.y, K_D, PL_L1, PL_L2, PL_D, ls1,ls2,ls3,lh1,lh2,lh3,pss,bepsi,lcu,PC1,PC2,PC3,PC4))
# with outlier
resmbmftb = table4(mbmftb)
resmbmftb
#resmbmft$P<0.05
```



